apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: udemy-microsrv-cluster
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  name: udemy-microsrv-payment
type: Opaque
data:
  stripe_secret_key: {{ .Values.secrets.payment__stripe_secret_key | b64enc | quote }}
  stripe_webhook_secret: {{ .Values.secrets.payment__stripe_webhook_secret | b64enc | quote }}
