version: "3"
services:
  nats-main:
    image: nats:2.11
    container_name: nats-main
    hostname: nats-main

  udemy-microsrv-gateway:
    build:
      context: ./udemy-microsrv-gateway
      dockerfile: Dockerfile.prod
    image: us-central1-docker.pkg.dev/udemy-microsrv/docker-images/udemy-microsrv-gateway
    container_name: udemy-microsrv-gateway
    hostname: udemy-microsrv-gateway
    ports:
      - "${GATEWAY_PORT}:3000"
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-main:4222

  udemy-microsrv-auth:
    build:
      context: ./udemy-microsrv-auth
      dockerfile: Dockerfile.prod
    image: us-central1-docker.pkg.dev/udemy-microsrv/docker-images/udemy-microsrv-auth
    container_name: udemy-microsrv-auth
    hostname: udemy-microsrv-auth
    environment:
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - NATS_SERVERS=nats://nats-main:4222
      - JWT_SECRET=${AUTH_JWT_SECRET}

  udemy-microsrv-product:
    build:
      context: ./udemy-microsrv-product
      dockerfile: Dockerfile.prod
    image: us-central1-docker.pkg.dev/udemy-microsrv/docker-images/udemy-microsrv-product
    container_name: udemy-microsrv-product
    hostname: udemy-microsrv-product
    environment:
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-main:4222

  udemy-microsrv-order:
    build:
      context: ./udemy-microsrv-order
      dockerfile: Dockerfile.prod
    image: us-central1-docker.pkg.dev/udemy-microsrv/docker-images/udemy-microsrv-order
    container_name: udemy-microsrv-order
    hostname: udemy-microsrv-order
    environment:
      - DATABASE_URL=${ORDER_DATABASE_URL}
      - NATS_SERVERS=nats://nats-main:4222

  udemy-microsrv-payment:
    build:
      context: ./udemy-microsrv-payment
      dockerfile: Dockerfile.prod
    image: us-central1-docker.pkg.dev/udemy-microsrv/docker-images/udemy-microsrv-payment
    container_name: udemy-microsrv-payment
    hostname: udemy-microsrv-payment
    ports:
      - "${PAYMENT_PORT}:3000"
    environment:
      - PORT=3000
      - STRIPE_SECRET_KEY=${PAYMENT_STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${PAYMENT_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENT_STRIPE_CANCEL_URL}
      - STRIPE_WEBHOOK_SECRET=${PAYMENT_STRIPE_WEBHOOK_SECRET}
      - NATS_SERVERS=nats://nats-main:4222
