version: "3"
services:
  nats-main:
    image: nats:2.11
    container_name: udemy-microsrv__nats-main
    hostname: udemy-microsrv__nats-main
    ports:
      - "4422:4422"
      - "8222:8222"

  udemy-microsrv-gateway:
    build: ./udemy-microsrv-gateway
    container_name: udemy-microsrv__gateway
    hostname: udemy-microsrv__gateway
    ports:
      - "3000:3000"
    volumes:
      - ./udemy-microsrv-gateway/src:/usr/src/app/src
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://udemy-microsrv__nats-main:4222

  udemy-microsrv-product:
    build: ./udemy-microsrv-product
    container_name: udemy-microsrv__product
    hostname: udemy-microsrv__product
    volumes:
      - ./udemy-microsrv-product/src:/usr/src/app/src
    environment:
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://udemy-microsrv__nats-main:4222
