apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: udemy-microsrv-gateway
  name: udemy-microsrv-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udemy-microsrv-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: udemy-microsrv-gateway
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/udemy-microsrv/docker-images/udemy-microsrv-gateway
        name: udemy-microsrv-gateway
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: nats://nats-main:4222
        resources: {}
status: {}
